samples:
  - SRR15618888
  - SRR15618889
  - SRR15618890
  - SRR15618895
  - SRR15618896
  - SRR15618897

input_path: "/opt/students/inga.bikulciene/raw_data_exercise_20260218"

genome_index: "/opt/shared/SYSBIO/Mus_musculus.GRCm39/genome"
gtf: "/opt/shared/SYSBIO/Mus_musculus.GRCm39/genome.gtf"
